name: Shrijan Tiwari
url: https://shrijan42.github.io/
designation: 
baseurl: /
about_me: Graduated Master of Science in Computer Game Engineering from Newcastle University. I have over 5 years of work experience as a Front End Developer/Software Developer. My Technical Skills are JavaScript, Unreal Engine, Unity, TypeScript, Angular, Lua , C++, C#, GDevelop 5, Vue.js, RPG Maker, Bootstrap, OpenGL , Java, SASS, HTML, CSS, Strapi CMS, MySQL, React, jQuery, LESS.js , ASP.NET , AngularJS , MongoDB , Express.js and Node.js.