name: Shrijan Tiwari
url: https://shrijan42.github.io/
designation: 
baseurl: /
about_me: Currently studying Master of Science in Computer Game Engineering at Newcastle University. I have had around 3 years of work experience as a Front End Developer/Software Developer. My Technical Skills are Javascript, Unreal Engine, Unity, Typescript, Angular, Lua , C++, C#, LESS, Bootstrap, Open Gl , Java, SASS, Vue, HTML, CSS, 3DS Max, Adobe Photoshop and Blender.