name: Shrijan Tiwari
url: https://shrijan42.github.io/
designation: 
baseurl: /
about_me: Recently completed my Master of Science in Computer Game Engineering from Newcastle University. I have over 3 years of work experience as a Front End Developer/Software Developer. My Technical Skills are JavaScript, Unreal Engine, Unity, TypeScript, Angular, Lua , C++, C#, React, Vue.js, LESS, Bootstrap, OpenGL , Java, SASS, HTML, CSS, Autodesk 3ds Max, Adobe Photoshop, Blender, jQuery and Node.js.